let mySprite = sprites.create(img`
    ......eeeee.............
    ....eeeeeeeee...........
    ....eeddddeeee..........
    ....edddddddee..........
    .....ddfddfdd...........
    .....dddddddd...........
    .....dddddddd...........
    .......dddd.............
    .......cccc.............
    .....cccccccc...........
    ...cccccccccccc.........
    ...cccccccccccc.........
    ...cccccccccccc.........
    ...cccccccccccc.........
    ..ddccccccccccdd........
    ..dd..cccccc..dd........
    ......cc..cc............
    ......cc..cc............
    ......cc..cc............
    ......cc..cc............
    ......cc..cc............
    ......dd..dd............
    ........................
    ........................
    `, SpriteKind.Player)
